### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by bisherbas** [Magisk-Modules-Repo/Battery-Life-Extender#1]
Can you provide an example command for auto switch feature? I can't seem to get the `blex` command to work with various parameters I have tried so far.

**Comment by sjayminsgithub** [comment]
I will include examples for every valid blex command in the next release. Until then, what thresholds are you trying to set ??

**Comment by sjayminsgithub** [comment]
I think [this commit](703449cc405d94a7bdec98dbffe0b321359da781) fixes the issue, gonna close it now.

**Comment by bisherbas** [comment]
Thanks!
